// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono4
//    unicode_glyphs | ĄȽɂɻɣɈʣ
//    output         | qmk_userspace
//    input          | noto11.png

#pragma once

#include "painter/qp.h"

extern const uint32_t font_noto11_length;
extern const uint8_t  font_noto11[1980];
