#pragma once

#define MASTER_RIGHT

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define FLOW_TAP 150

#define COMBO_STRICT_TIMER

#define ENCODER_RESOLUTION 2

